# ============================
# Projeto
# Referência: https://packaging.python.org/en/latest/guides/writing-pyproject-toml/
# 

# Instale o pacote: python-dotenv
# Mostrei como no README.md
# 

# Os pontos de atenção estão comentados próximo das chaves, aqui só coloquei um
# lembrete
# 

# Atenção: As versões do Python devem ser consistentes entre:
#                 - project.requires-python
#                    - tool.ruff.target-version
#                   - tool.pyright.pythonVersion
# 

# Atenção: O nome do pacote principal deve ser consistente entre:
#                - project.scripts
#                - tool.ruff.lint.isort.known-first-party
#                - A pasta dentro de 'src/'
# 

# Thanks = 'https://www.otaviomiranda.com.br/'
# Thanks to Otávio Miranda for providing this template file
# ============================

[project]
name = "teste"
version = "1.0.0"
description = "teste"
readme = "README.md"
requires-python = "==3.14.3"
dependencies = [
    "tomlkit>=0.15.0",
]
authors = [{name = "user",email = "example@example.com"}]

[project.urls]
Repository = "https://github.com/user/teste"

[project.scripts]
# Define os comandos de console. A chave ('teste')
# é o comando.
# O valor aponta para 'nome_do_pacote.nome_do_modulo:nome_da_funcao'.
# Ex: 'my_package.main:run'
# -> src/my_package/main.py (e a função run lá dentro).
# Lembre de sincronizar o nome do pacote com 'known-first-party' do Ruff
# teste = "my_package.my_module:function
pproject = "main:main"


[tool.ruff]
# ============================
# Lint e formatação (Ruff)
# ============================
line-length = 88
target-version = "py314"
fix = true
show-fixes = true
indent-width = 4
exclude = ["venv", ".venv", "env", ".env", "node_modules", "__pycache__"]

[tool.ruff.lint]
fixable = ["ALL"]
select = ["ASYNC", "A", "ANN", "B", "BLE", "C4", "C90", "COM", "E", "EM", "ERA", "EXE", "F", "FBT", "FIX", "I", "ICN", "ISC", "Q", "RET", "RSE", "S", "SIM", "SLF", "T10", "T20", "TC", "TD", "TRY", "UP", "W", "YTT", "RUF", "N"]
ignore = ["T201", "COM812", "S603", "S605", "S607"]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["ANN201", "S101"]

[tool.ruff.lint.isort]
known-first-party = ["src", "my_package"]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "cr-lf"

[tool.pyright]
# ============================
# Tipagem (Pyright)
# ============================
typeCheckingMode = "strict"
pythonVersion = "3.14.3"
include = ["src", "tests"]
exclude = ["**/venv", "**/.venv", "**/env", "**/.env", "**/node_modules", "**/__pycache__", "**/.*"]
venv = ".venv"
venvPath = "."

[[tool.pyright.executionEnvironments]]
root = "src"

[tool.pytest.ini_options]
addopts = "-s --color=yes --tb=short"
pythonpath = ["src"]
testpaths = ["tests"]

[tool.hatch.build.targets.wheel]
packages = ["src", "src/my_package"]

[tool.uv.workspace]
members = []

[build-system]
# ============================
# Build
# ============================
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.4.0",
    "pytest-xdist>=3.7.0",
    "ruff>=0.11.12",
]
